In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [2]:
def q(b,eps):
    m = 2; delf = 2/(m+1)
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    return (x/(2*((x+1)**2)*(y-1)))*((y-1)*(y*z-1)-delf*(y/x)*(m*y*z-(m+1)*z+1))
            
def X(b,eps):
    m = 2
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    return (y*z)/(2*q(b,eps)*(x+1))

def Y1(b,eps):
    m = 2; delf = 2/(m+1)
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    Y = (x/(2*q(b,eps)*(x+1)))*(1+delf*(y/x)*(m*z-(z-1)/(y-1)))
    return Y

In [3]:
def D(b,eps):
    m = 2
    qq = q(b,eps); XX = X(b,eps); YY1 = Y1(b,eps)
    return XX + YY1

In [4]:
m = 2

delf = 2/(m+1)

Ds = np.zeros((4,6))
bs = [1, (2*m+7)/(2*(m+4)), (m+3)/(m+4), (2*m+5)/(2*(m+4))]
epss = [0.2, 0.5, 1, 2, 5, 10]

for i in range(4):
    for j in range(6):
        y = math.exp(epss[j])
        A = delf*(y*(y**m-1)/(y-1)); B = (1+m*delf)*(y**(m+1))
        U = epss[j]/(math.log((A+math.sqrt(A**2+4*B))/2))
        Ds[i][j] = D(bs[i]*U,epss[j])

print(Ds)

[[11.78792453  5.24784953  3.23085927  2.47393153  2.33384235  2.33333336]
 [11.85118474  5.29704124  3.27690737  2.51003283  2.34018452  2.33348284]
 [12.0591001   5.44525865  3.40549366  2.60325846  2.36097209  2.33482737]
 [12.49884838  5.75717459  3.68055674  2.81802004  2.44483908  2.35408699]]
