In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [2]:
def q(b,eps):
    m = 1; delf = 2/(m+1)
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    return (x/(2*((x+1)**2)*(y-1)))*((y-1)*(y*z-1)-delf*(y/x)*(m*y*z-(m+1)*z+1))
            
def X(b,eps):
    m = 1
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    return (y*z)/(2*q(b,eps)*(x+1))

def Y1(b,eps):
    m = 1; delf = 2/(m+1)
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    Y = (x/(2*q(b,eps)*(x+1)))*(1+delf*(y/x)*(m*z-(z-1)/(y-1)))
    return Y

In [3]:
def D(b,eps):
    m = 1
    qq = q(b,eps); XX = X(b,eps); YY1 = Y1(b,eps)
    return XX + YY1

In [4]:
m = 1

delf = 2/(m+1)

Ds = np.zeros((4,6))
bs = [1, (2*m+7)/(2*(m+4)), (m+3)/(m+4), (2*m+5)/(2*(m+4))]
epss = [0.2, 0.5, 1, 2, 5, 10]

for i in range(4):
    for j in range(6):
        y = math.exp(epss[j])
        A = delf*(y*(y**m-1)/(y-1)); B = (1+m*delf)*(y**(m+1))
        U = epss[j]/(math.log((A+math.sqrt(A**2+4*B))/2))
        Ds[i][j] = D(bs[i]*U,epss[j])

print(Ds)

[[15.5499667   6.62448225  3.74593012  2.46955293  2.02035096  2.00013621]
 [15.6114538   6.66494994  3.7799217   2.49557668  2.02593571  2.00028019]
 [15.85322726  6.82452036  3.9156245   2.6034036   2.05260821  2.00127634]
 [16.42020787  7.20275899  4.24656999  2.88734909  2.14921443  2.00883446]]
