In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [2]:
def q(b,eps):
    m = 0; delf = 2/(m+1)
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    return (x/(2*((x+1)**2)*(y-1)))*((y-1)*(y*z-1)-delf*(y/x)*(m*y*z-(m+1)*z+1))
            
def X(b,eps):
    m = 0
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    return (y*z)/(2*q(b,eps)*(x+1))

def Y1(b,eps):
    m = 0; delf = 2/(m+1)
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    Y = (x/(2*q(b,eps)*(x+1)))*(1+delf*(y/x)*(m*z-(z-1)/(y-1)))
    return Y

In [3]:
def D(b,eps):
    m = 0
    qq = q(b,eps); XX = X(b,eps); YY1 = Y1(b,eps)
    return XX + YY1

In [4]:
m = 0

delf = 2/(m+1)

Ds = np.zeros((4,6))
bs = [1, (2*m+7)/(2*(m+4)), (m+3)/(m+4), (2*m+5)/(2*(m+4))]
epss = [0.2, 0.5, 1, 2, 5, 10]

for i in range(4):
    for j in range(6):
        y = math.exp(epss[j])
        A = delf*(y*(y**m-1)/(y-1)); B = (1+m*delf)*(y**(m+1))
        U = epss[j]/(math.log((A+math.sqrt(A**2+4*B))/2))
        Ds[i][j] = D(bs[i]*U,epss[j])

print(Ds)

[[20.01666389  8.04162333  4.08298817  2.16395341  1.17885098  1.01356731]
 [20.01768262  8.04414824  4.08788574  2.17265103  1.18950455  1.01715387]
 [20.02221071  8.05537655  4.10970318  2.21166598  1.23964017  1.03703911]
 [20.03463932  8.08624154  4.16999435  2.32176913  1.4023822   1.13576771]]
