In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [2]:
def q(b,eps):
    m = 3; delf = 2/(m+1)
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    return (x/(2*((x+1)**2)*(y-1)))*((y-1)*(y*z-1)-delf*(y/x)*(m*y*z-(m+1)*z+1))
            
def X(b,eps):
    m = 3
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    return (y*z)/(2*q(b,eps)*(x+1))

def Y1(b,eps):
    m = 3; delf = 2/(m+1)
    x = math.exp(eps/b); y = math.exp(eps); z = y**m
    Y = (x/(2*q(b,eps)*(x+1)))*(1+delf*(y/x)*(m*z-(z-1)/(y-1)))
    return Y

In [3]:
def D(b,eps):
    m = 3
    qq = q(b,eps); XX = X(b,eps); YY1 = Y1(b,eps)
    return XX + YY1

In [4]:
m = 3

delf = 2/(m+1)

Ds = np.zeros((4,6))
bs = [1, (2*m+7)/(2*(m+4)), (m+3)/(m+4), (2*m+5)/(2*(m+4))]
epss = [0.2, 0.5, 1, 2, 5, 10]

for i in range(4):
    for j in range(6):
        y = math.exp(epss[j])
        A = delf*(y*(y**m-1)/(y-1)); B = (1+m*delf)*(y**(m+1))
        U = epss[j]/(math.log((A+math.sqrt(A**2+4*B))/2))
        Ds[i][j] = D(bs[i]*U,epss[j])

print(Ds)

[[ 9.49451853  4.42474859  2.96155623  2.53381832  2.50000531  2.5       ]
 [ 9.55084726  4.47507752  3.01203952  2.57276562  2.50681465  2.50019362]
 [ 9.71018053  4.59902568  3.12314616  2.65411374  2.53348203  2.50297887]
 [10.02254223  4.83695997  3.33720888  2.82844823  2.66489191  2.56716189]]
